### ISSUE TITLE
Mismatch between paper and code

### ISSUE THREAD

**Issue by hal-314** [human-analysis/neural-architecture-transfer#2]
Hi!
Your paper is fantastic. I notice a small mismatch between the paper and the code. In section "3.2    Search Space and Encoding", paper says "Each stage in turn comprises multiple layers, and each layer it self is an inverted residual bottleneck structure [54]." and the same can be seen in figure 2a. However, your inverted residual is different from inverted residual block proposed in MobileNetV2. 

Specifically, the [line 43](https://github.com/human-analysis/neural-architecture-transfer/blob/master/codebase/networks/natnet.py#L43) (`res += self.shortcut(x)`). MobileNetV2 inverted residual block doesn't apply the shortcut.

It's a bug on the released code or it's a deliberated change? If it's the second, I think that should be stated in the section 3.2 and figure 2a of the paper, 

`MobileInvertedResidualBlock` code: 
```
class MobileInvertedResidualBlock(MyModule):

    def __init__(self, mobile_inverted_conv, shortcut, drop_connect_rate=0.0):
        super(MobileInvertedResidualBlock, self).__init__()

        self.mobile_inverted_conv = mobile_inverted_conv
        self.shortcut = shortcut
        self.drop_connect_rate = drop_connect_rate

    def forward(self, x):
        if self.mobile_inverted_conv is None or isinstance(self.mobile_inverted_conv, ZeroLayer):
            res = x
        elif self.shortcut is None or isinstance(self.shortcut, ZeroLayer):
            res = self.mobile_inverted_conv(x)
        else:
            # res = self.mobile_inverted_conv(x) + self.shortcut(x)
            res = self.mobile_inverted_conv(x)

            if self.drop_connect_rate > 0.:
                res = drop_connect(res, self.training, self.drop_connect_rate)

            res += self.shortcut(x)  # <- here is the difference. Standard residual block is res += x

        return res
```

**Comment by mikelzc1990** [comment]
The shortcut here is simply an [identity layer](https://github.com/human-analysis/neural-architecture-transfer/blob/5aca00a11b22902a9e7b2f9c33b58bc4ba686828/codebase/modules/layers.py#L303), please see [network config file](https://github.com/human-analysis/neural-architecture-transfer/blob/5aca00a11b22902a9e7b2f9c33b58bc4ba686828/subnets/imagenet/NAT-M1/net.config#L38). It is equivalent as *res += x*.
